import { DeviceArchivedDocumentDetail } from './DeviceArchivedDocumentDetail';
import { DeviceAvailableDocumentDetail } from './DeviceAvailableDocumentDetail';
import { DeviceAvailableFormDetail } from './DeviceAvailableFormDetail';
import { DeviceArchivedWorkPermitDetail } from './DeviceArchivedWorkPermitDetail';
import { DeviceAvailableWorkPermitDetail } from './DeviceAvailableWorkPermitDetail';
import { DeviceCheckInGuestInductionItemDetail } from './DeviceCheckInGuestInductionItemDetail';
import { DeviceDetailData } from './DeviceDetailData';
import { DeviceEntityData } from './DeviceEntityData';
import { DeviceHazardItemDetail } from './DeviceHazardItemDetail';
import { DeviceRiskItemDetail } from './DeviceRiskItemDetail';
import { DeviceHAVModelDetail } from './DeviceHAVModelDetail';
import { DeviceHAVTypeDetail } from './DeviceHAVTypeDetail';
import { DeviceHAVManufacturerDetail } from './DeviceHAVManufacturerDetail';
import { DeviceCompanyUserGroupDetail } from './DeviceCompanyUserGroupDetail';
import { DeviceCompanyUserDetail } from './DeviceCompanyUserDetail';
import { DeviceUserDetail } from './DeviceUserDetail';
import { DeviceUserQualificationDetail } from './DeviceUserQualificationDetail';
import { DeviceGuestUserDetail } from './DeviceGuestUserDetail';
import { DeviceLiveWorkPermitDetail } from './DeviceLiveWorkPermitDetail';
import { DeviceFormDetail } from './DeviceFormDetail';
import { DeviceFormAttachmentDetail } from './DeviceFormAttachmentDetail';
import { DeviceEvacuationDetail } from './DeviceEvacuationDetail';
import { DeviceUserCheckInQualificationDetail } from './DeviceUserCheckInQualificationDetail';
import { DeviceLocationDetail } from './DeviceLocationDetail';
import { DeviceProjectDetail } from './DeviceProjectDetail';
import { DeviceInventoryItemDetail } from './DeviceInventoryItemDetail';
import { DeviceUserCheckinDetail } from './DeviceUserCheckinDetail';
import { DeviceCheckInGuestInductionDetail } from './DeviceCheckInGuestInductionDetail';
import { DeviceCheckInInductionItemDetail } from './DeviceCheckInInductionItemDetail';
import { DeviceGuestUserCheckinDetail } from './DeviceGuestUserCheckinDetail';

export class DeviceOfflineDetailViewModels {
	DeviceDetailData: DeviceDetailData;
	DeviceEntityData: Array<DeviceEntityData>;
	DeviceUserList: Array<DeviceUserDetail>;
	DeviceUserQualificationList: Array<DeviceUserQualificationDetail>;
	DeviceGuestUserList: Array<DeviceGuestUserDetail>;
	DeviceAvailableDocumentList: Array<DeviceAvailableDocumentDetail>;
	DeviceArchivedDocumentList: Array<DeviceArchivedDocumentDetail>;
	DeviceAvailableFormList: Array<DeviceAvailableFormDetail>;
	DeviceArchivedFormList: Array<DeviceArchivedDocumentDetail>;
	DeviceAvailableWorkPermitList: Array<DeviceAvailableWorkPermitDetail>;
	DeviceLiveWorkPermitList: Array<DeviceLiveWorkPermitDetail>;
	DeviceArchivedWorkPermitList: Array<DeviceArchivedWorkPermitDetail>;
	DeviceFormDetailsList: Array<DeviceFormDetail>;
	DeviceFormAttachmentList: Array<DeviceFormAttachmentDetail>;
	DeviceEvacuationList: Array<DeviceEvacuationDetail>;
	DeviceUserCheckInQualificationList: Array<DeviceUserCheckInQualificationDetail>;
	DeviceLocationList: Array<DeviceLocationDetail>;
	DeviceProjectList: Array<DeviceProjectDetail>;
	DeviceInventoryItemList: Array<DeviceInventoryItemDetail>;
	DeviceUserCheckinDetailList: Array<DeviceUserCheckinDetail>;
	DeviceCheckInInductionList: Array<DeviceCheckInGuestInductionDetail>;
	DeviceCheckInInductionItemList: Array<DeviceCheckInInductionItemDetail>;
	DeviceGuestUserCheckinDetailList: Array<DeviceGuestUserCheckinDetail>;
	DeviceCheckInGuestInductionList: Array<DeviceCheckInGuestInductionDetail>;
	DeviceCheckInGuestInductionItemList: Array<DeviceCheckInGuestInductionItemDetail>;
	DeviceCompanyUserList: Array<DeviceCompanyUserDetail>;
	DeviceCompanyUserGroupList: Array<DeviceCompanyUserGroupDetail>;
	DeviceHAVManufacturerList: Array<DeviceHAVManufacturerDetail>;
	DeviceHAVTypeList: Array<DeviceHAVTypeDetail>;
	DeviceHAVModelList: Array<DeviceHAVModelDetail>;
	DeviceRiskItemList: Array<DeviceRiskItemDetail>;
	DeviceHazardItemList: Array<DeviceHazardItemDetail>;
}
